### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [crutchcorn/stagger#43]
```
What steps will reproduce the problem?
1. python 3.3.2
2. Arch Linux PKGBUILD
3. ython setup.py install --root="${pkgdir}/" --optimize=1 || return 1

What is the expected output? What do you see instead?

error: invalid command 'bdist_egg'
/home/tilaa/aur/python3-stagger-svn/python3-stagger-svn/distribute-0.6.15-py3.3.
egg
Traceback (most recent call last):
  File "/home/tilaa/aur/python3-stagger-svn/python3-stagger-svn/distribute_setup.py", line 143, in use_setuptools
    raise ImportError
ImportError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    distribute_setup.use_setuptools()
  File "/home/tilaa/aur/python3-stagger-svn/python3-stagger-svn/distribute_setup.py", line 145, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/tilaa/aur/python3-stagger-svn/python3-stagger-svn/distribute_setup.py", line 125, in _do_download
    _build_egg(egg, tarball, to_dir)
  File "/home/tilaa/aur/python3-stagger-svn/python3-stagger-svn/distribute_setup.py", line 116, in _build_egg
    raise IOError('Could not build the egg.')
OSError: Could not build the egg.

What version of the product are you using? On what operating system?
Arch Linux Python 3.3.2

Please provide any additional information below.


PKGBUILD: http://p.osuv.de/mQn4/
```

Original issue reported on code.google.com by `marku...@gmail.com` on 22 Aug 2013 at 5:22

**Comment by crutchcorn** [comment]
Followed Miohtama's Bitbucket. Fix will be pushed soon
